"""
Django settings for ischoolbus project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'f!*eep0b7c-_1ly#g%9$k01+3y6=thvcuexj5vrpr+8p0v3r+1'

# Application definition

INSTALLED_APPS = [
    'core',
    'settings',
    'easy_thumbnails',
    'filer',
    'mptt',
    'ckeditor',
    'corsheaders',
    'rest_framework',
    'mailer',
    "fcm_django",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'daterangefilter',
]

EMAIL_BACKEND = "mailer.backend.DbBackend"

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ischoolbus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ischoolbus.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
UPLOADS_FOLDER = os.path.join('static', 'uploads')
MEDIA_ROOT = os.path.join(BASE_DIR, UPLOADS_FOLDER)
STATIC_ROOT = os.path.join(BASE_DIR, "static/")

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS':
    'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE':
    10,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'EXCEPTION_HANDLER':
    'infra.exceptions.rest_exception_handler'
}

CKEDITOR_UPLOAD_PATH = MEDIA_ROOT
CKEDITOR_CONFIGS = {'default': {'toolbar': 'full', 'entities_latin': False}}

PRODUCTION_URL = "/"
CORS_ORIGIN_ALLOW_ALL = True

CONTACT_US_EMAIL = os.environ.get('CONTACT_US_EMAIL', 'thaitcao@gmail.com')

# for django filer
FILER_DEBUG = True
FILER_ENABLE_LOGGING = True
THUMBNAIL_HIGH_RESOLUTION = True
THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'easy_thumbnails.processors.scale_and_crop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters',
)

MAX_RECORDS_PER_PAGE = 20

FCM_DJANGO_SETTINGS = {
    "APP_VERBOSE_NAME": "iSchoolBusBackend",
    # default: _('FCM Django')
    # "FCM_SERVER_KEY": "AAAAQKX9J3o:APA91bHe4vG_GtrnY1juAkiEMMKwRGwRVI_QbFI92i4U20vE0ypAawA9ACA2X48jbPtwdootYJN01UsGl_S2VfA2jwhS674ZpHY1Q2BVtcVugl5jwFtHbX0sIJao9coSvpJHRG8tw4mZ",
    "FCM_SERVER_KEY":
    "AAAAFRlD_2Q:APA91bEM11Hkejxv655vBtKgeqRHBH30p4hD1x2huk5EWPehpc5U3QurehtKe58-xice8JNGLbTCw6D53robxFQhosBMgK8cOjj6hKwlYAxxABzcYB-LMM1QvCsRBqIwMzCMrWWZNJxq",
    # true if you want to have only one active device per registered user at a time
    # default: False
    "ONE_DEVICE_PER_USER": False,
    # devices to which notifications cannot be sent,
    # are deleted upon receiving error response from FCM
    # default: False
    "DELETE_INACTIVE_DEVICES": False,
}
