# Generated by Django 2.2.3 on 2019-11-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191118_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='id_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
