# Generated by Django 2.2.4 on 2019-11-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191118_1951'),
        ('core', '0004_auto_20191118_2020'),
    ]

    operations = [
    ]
