# Generated by Django 2.2.4 on 2019-11-19 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191119_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='driver',
        ),
        migrations.AddField(
            model_name='busroute',
            name='bus',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Bus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busroute',
            name='bus_supervisor',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.BusSupervisor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busroute',
            name='driver',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Driver'),
            preserve_default=False,
        ),
    ]
