# Generated by Django 2.2.3 on 2019-11-19 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191119_1252'),
        ('core', '0006_auto_20191119_1000'),
    ]

    operations = [
    ]
