# Generated by Django 2.2.4 on 2019-11-19 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191119_1252'),
        ('core', '0006_merge_20191118_2025'),
    ]

    operations = [
    ]
