# Generated by Django 2.2.3 on 2019-11-20 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20191119_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='buslocation',
            name='lat',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buslocation',
            name='lng',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buslocation',
            name='students',
            field=models.ManyToManyField(to='core.Student'),
        ),
        migrations.AddField(
            model_name='buslocation',
            name='time_to_next_location',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='busroute',
            name='route_type',
            field=models.CharField(choices=[('P', 'Pick-up'), ('D', 'Drop-off')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='buslocation',
            name='next_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BusLocation'),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bus'),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='bus_supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BusSupervisor'),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Driver'),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='first_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BusLocation'),
        ),
    ]
