# Generated by Django 2.2.3 on 2019-11-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191119_1831'),
        ('core', '0009_auto_20191120_1549'),
    ]

    operations = [
    ]
