# Generated by Django 2.2.3 on 2019-11-20 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20191120_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='status',
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.School'),
        ),
    ]
