# Generated by Django 2.2.3 on 2019-11-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191120_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bus_registerd_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
