# Generated by Django 2.2.4 on 2019-11-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191120_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='id_number',
        ),
    ]
