# Generated by Django 2.2.3 on 2019-11-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191120_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='alternative_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
