# Generated by Django 2.2.4 on 2019-11-22 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20191121_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='avatar',
            new_name='logo',
        ),
    ]
