# Generated by Django 2.2.4 on 2019-11-22 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191122_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buslocation',
            name='next_location',
        ),
        migrations.RemoveField(
            model_name='buslocation',
            name='students',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='first_location',
        ),
        migrations.CreateModel(
            name='BusLocationWithStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, editable=False, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, editable=False, null=True)),
                ('bus_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BusLocation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusRouteWithLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, editable=False, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, editable=False, null=True)),
                ('order', models.IntegerField(default=0)),
                ('bus_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BusLocation')),
                ('bus_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BusRoute')),
            ],
            options={
                'unique_together': {('order', 'bus_route')},
            },
        ),
    ]
