# Generated by Django 2.2.4 on 2019-11-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20191122_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
