# Generated by Django 2.2.3 on 2019-11-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_busroute_is_running'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussupervisor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='bussupervisor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
