# Generated by Django 2.2.3 on 2019-11-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20191124_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='info',
        ),
    ]
