# Generated by Django 2.2.3 on 2019-11-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_driver_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
