# Generated by Django 2.2.3 on 2019-11-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20191124_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buslocation',
            name='time_to_next_location',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
