# Generated by Django 2.2.3 on 2019-11-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20191124_1619'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buslocationwithstudents',
            unique_together={('student', 'bus_location')},
        ),
    ]
