# Generated by Django 2.2.1 on 2019-11-25 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20191124_1621'),
        ('core', '0016_student_alternative_name'),
    ]

    operations = [
    ]
