# Generated by Django 2.2.4 on 2019-11-25 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20191124_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='estimated_start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, editable=False, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, editable=False, null=True)),
                ('status', models.IntegerField()),
                ('current_date', models.DateField(auto_now_add=True)),
                ('bus_location_with_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BusLocationWithStudents')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
