# Generated by Django 2.2.4 on 2019-11-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20191125_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='estimated_start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
