# Generated by Django 2.2.1 on 2019-11-25 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_merge_20191125_1030'),
        ('core', '0027_auto_20191125_1223'),
    ]

    operations = [
    ]
