# Generated by Django 2.2.1 on 2019-11-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_merge_20191125_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='buslocation',
            name='polygon_to_next_location',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
