# Generated by Django 2.2.1 on 2019-11-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20191125_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='end_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
