# Generated by Django 2.2.1 on 2019-11-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20191125_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buslocation',
            name='time_to_next_location',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
