# Generated by Django 2.2.1 on 2019-11-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_buslocation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='id_number',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
