# Generated by Django 2.2.4 on 2019-11-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20191126_1308'),
        ('core', '0034_parent_id_number'),
    ]

    operations = [
    ]
