# Generated by Django 2.2.4 on 2019-11-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_merge_20191126_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buslocation',
            name='number',
        ),
        migrations.AlterField(
            model_name='buslocation',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buslocation',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buslocation',
            name='polygon_to_next_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buslocation',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buslocation',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
