# Generated by Django 2.2.1 on 2019-11-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20191126_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='buslocation',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
