# Generated by Django 2.2.4 on 2019-11-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_buslocation_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='reason_for_absence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
