# Generated by Django 2.2.4 on 2019-11-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_attendance_reason_for_absence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='reason_for_absence',
            new_name='reason_for_absence_missing',
        ),
    ]
