# Generated by Django 2.1.7 on 2019-12-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20191128_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='estimated_end_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
