# Generated by Django 2.1.7 on 2019-12-10 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20191206_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRouteHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, editable=False, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, editable=False, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Stopping'), (1, 'Running')], default=0)),
                ('bus_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BusRoute')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
