# Generated by Django 2.1.7 on 2019-12-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_busroutehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroutewithlocation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not reach'), (1, 'Passed')], default=0),
        ),
    ]
