# Generated by Django 2.1.7 on 2019-12-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_busroutewithlocation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buslocation',
            old_name='time_to_next_location',
            new_name='estimated_travelling_time',
        ),
    ]
