# Generated by Django 2.1.7 on 2019-12-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20191211_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buslocation',
            name='estimated_travelling_time',
        ),
        migrations.AddField(
            model_name='busroutewithlocation',
            name='estimated_travelling_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
