# Generated by Django 2.1.7 on 2019-12-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20191212_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='current_date',
            field=models.DateField(),
        ),
    ]
