# Generated by Django 2.1.7 on 2019-12-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20191219_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
