# Generated by Django 2.1.7 on 2019-12-20 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20191219_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='bus_location_with_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.BusLocationWithStudents'),
        ),
    ]
