# Generated by Django 2.1.7 on 2019-12-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20191220_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='report_absence_by_parent',
            field=models.BooleanField(default=False),
        ),
    ]
