# Generated by Django 2.1.7 on 2020-01-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_attendance_report_absence_by_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='id_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
