# Generated by Django 2.1.7 on 2020-01-10 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_language_notificationtemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationtemplate',
            old_name='langage',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='notificationtemplate',
            old_name='template',
            new_name='text',
        ),
    ]
