# Generated by Django 2.1.7 on 2020-01-10 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20200110_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, editable=False, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, editable=False, null=True)),
                ('route_type', models.CharField(max_length=100)),
                ('route_name', models.CharField(max_length=500)),
                ('end_time', models.DateField()),
                ('sender', models.CharField(max_length=200)),
                ('receiver', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.CharField(max_length=500)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
