# Generated by Django 2.1.7 on 2020-01-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_notificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='student',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
