# Generated by Django 2.1.7 on 2020-01-10 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20200110_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationlog',
            name='end_time',
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='logging_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
