# Generated by Django 2.1.7 on 2020-01-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20200110_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationtemplate',
            old_name='text',
            new_name='en_text',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='language',
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='vn_text',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
