# Generated by Django 2.1.7 on 2020-02-17 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20200217_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='additional_contact_info',
        ),
        migrations.AddField(
            model_name='contact',
            name='student',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='core.Student'),
        ),
    ]
