# Generated by Django 2.1.7 on 2020-02-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20200217_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='relationship',
            field=models.CharField(default='mother', max_length=50),
            preserve_default=False,
        ),
    ]
